steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    timeout: 2700s
    args:
      - --destination=europe-west2-docker.pkg.dev/${_PROJECT}/kraken-api/valuator:v1.1
      - --cache=true
      - --cache-ttl=24h
timeout: 2700s
options:
  machineType: E2_HIGHCPU_32
  logging: CLOUD_LOGGING_ONLY
