version: 2.1

docker:
  - image: google/cloud-sdk:437.0.0

jobs:
  rebuild-decoder-container:
    steps:
      - checkout
      - run:
          name: Check Active Account
          command: gcloud auth list

workflows:
  build:
    jobs:
      - rebuild-decoder-container: