version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest

  rebuild-decoder-container:
    docker:
      - image: google/cloud-sdk:<< parameters.gcp_sdk_version >>
    parameters:
      google_region:
        default: europe-west2
        description: The name of the environment variable containing the region in GCP.
        type: string
      gcp_sdk_version:
        default: 437.0.0
        description: The version to use for the GCP SDK.
        type: string
    steps:
      - checkout
      - run:
          name: Print Parameters
          command: |
            echo Authenticating Docker with Artifact Registry for << parameters.google_region >>-docker.pkg.dev            
            echo GCP SDK Version: << parameters.gcp_sdk_version >>

      - run:
          name: Authenticate Docker with Artifact Registry
          command: gcloud auth configure-docker << parameters.google_region >>-docker.pkg.dev

      - run:
          name: Submit new build
          command: gcloud builds submit --project=kraken-v2-dev --config /root/project/cloudbuild_valuator.yaml --substitutions="_PROJECT=kraken-v2-dev"

workflows:
  sample:
    jobs:
      - build-and-test
      - rebuild-decoder-container:
          requires:
            - build-and-test
