version: 2.1

orbs:
  python: circleci/python@1.5.0

parameters:
  google_region:
    default: GCP_REGION
    description: The name of the environment variable containing the region in GCP.
    type: string
  gcp_sdk_version:
      default: 437.0.0
      description: The version to use for the GCP SDK.

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest

  rebuild-decoder-container:
    docker:
      - image: google/cloud-sdk:<< parameters.gcp_sdk_version >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Authenticate Docker with Artifact Registry
          command: gcloud auth configure-docker "${!ORB_GOOGLE_REGION}-docker.pkg.dev"
          environment:
            ORB_GOOGLE_REGION: << parameters.google_region >>

workflows:
  sample:
    jobs:
      - build-and-test
      - rebuild-decoder-container:
          requires:
            - build-and-test
